name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: testApp
      run: |
          docker build . -t louis1212/node-js_sample:latest
          docker run -p 8080:8080 -d louis1212/node-js_sample:latest
          sleep 2
          curl I localhost:8080 | grep "200 OK"
    
  buildpush:
    needs: test

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        Username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/node-js_sample:latest
