name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: docker login
      uses: docker/login-action@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - 
      name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/node-js_sample:latest
